# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-11 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alternative_contact_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='alternative_contact_phonenumber',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
