# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-12 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171211_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offering',
            name='offering_end_date',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='offering_start_date',
        ),
        migrations.AddField(
            model_name='offering',
            name='address',
            field=models.CharField(default='13, model way', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offering',
            name='approved_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='counter_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offering',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True),
        ),
    ]
