# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-15 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20171212_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterOffering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(blank=True, max_length=70, null=True)),
                ('counter_price', models.IntegerField(blank=True, null=True)),
                ('counter_price_text', models.CharField(blank=True, max_length=250, null=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('approved_price', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='offering',
            name='approved_price',
        ),
        migrations.RemoveField(
            model_name='offering',
            name='counter_price',
        ),
    ]
