# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-16 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171215_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counteroffering',
            name='approved_price',
        ),
        migrations.RemoveField(
            model_name='counteroffering',
            name='counter_price',
        ),
        migrations.RemoveField(
            model_name='counteroffering',
            name='counter_price_text',
        ),
        migrations.RemoveField(
            model_name='counteroffering',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='offering',
            name='approved_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='counter_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='counter_price_text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
