# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-12-27 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20171216_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='previous_counter_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
