# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-04 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_offering_previous_counter_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteroffering',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counteroffering',
            name='date_last_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offering',
            name='date_last_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
