# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-04 23:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180104_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counteroffering',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='counteroffering',
            name='date_last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='offering',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='offering',
            name='date_last_modified',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
